### ISSUE TITLE
Morph Target CUBICSPLINE of multiple weights

### ISSUE THREAD

**Issue by sjfricke** [KhronosGroup/glTF#1344] opened 2018-05-21 01:23 UTC
For `CUBICSPLINE` it says there is three elements, an `in-tangent`, a `spline vertex`, and an `out-tangent`. If I have three weights does the output array per frame look like

`[in-tangent_0, spline_vertex_0, out-tangent_0, in-tangent_1, spline_vertex_1, out-tangent_1, in-tangent_2, spline_vertex_2, out-tangent_2]`

or

`[in-tangent_0, in-tangent_1, in-tangent_2, spline_vertex_0, spline_vertex_1, spline_vertex_2, out-tangent_0, out-tangent_1, out-tangent_2]`

Here is a Blender sample I made
![blender_screen_shot](https://user-images.githubusercontent.com/9061055/40286140-272b62f4-5c6a-11e8-8caa-6094ab1ed4e9.png)

Using the [Khronos Blender Exporter](https://github.com/KhronosGroup/glTF-Blender-Exporter) I get a sampler `output` of

```
0,   0,   0,         // frame 0
0 ,  0,   0, 
0,   0    0,
0.65460145, 0,  0,   // frame 1
0.5, 1, 0.25,
1.0172703, 0, 0,
0,   0,   0,         // frame 2
0 ,  0,   0, 
0,   0    0,
```

Which shows its the 2nd layout above, but there is nothing in the spec to my knowledge of constantly looking on the layout of multiple weights for CUBICSPLINE samplers per keyframe. From the response I got asking this in the Gitter shows there is ambiguity here

**Comment by lexaknyazev** [comment] 2018-05-21 02:11
@bghgary 
My understanding has always been that spline-animated morph weights follow this layout (the first in the post above):
```
[in0, w0, out0, in1, w1, out1, in2, w2, out2, ...] x number_of_frames
```

Khronos Blender Exporter writes all weights' input tangents together, then values, then output tangents. This could be seen from source code:
https://github.com/KhronosGroup/glTF-Blender-Exporter/blob/fa60cf5f63a567a2104a38d06fc91d001db16ff2/scripts/addons/io_scene_gltf2/gltf2_generate.py#L472-L479

What should be fixed: the spec or the exporter?

/cc @donmccurdy @McNopper

**Comment by bghgary** [comment] 2018-05-21 19:53
I have always used the 2nd layout in my implementations. I have been treating the weights as a single unit (similar to position, rotation, or scale vectors).

> What should be fixed: the spec or the exporter?

Either way, it sounds like there is confusion in the spec, so we should clarify the spec. But I believe the exporter is correct for this and we need to update the spec with a clarification.

**Comment by lexaknyazev** [comment] 2018-05-21 20:17
> I have always used the 2nd layout in my implementations.

Hmmm... That's interesting because I remember GitHub threads saying that it's the first.
Nevertheless, I like the second layout more and if it's already implemented that way in all engines we should add a note to the spec.

/cc @donmccurdy @emackey 
Could you please check with three.js and Cesium?

**Comment by emackey** [comment] 2018-05-21 21:47
Cubicspline appears to be unimplemented in Cesium.  Filed issue AnalyticalGraphicsInc/cesium#6609

**Comment by donmccurdy** [comment] 2018-05-21 22:06
I'm having trouble exporting morph targets as CUBICSPLINE from Blender — they seem to be baked to LINEAR per https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/216 — but the 2nd layout is what we've implemented, and probably my preference. If there is a `.gltf` file to test I wouldn't mind verifying we have that right.

**Comment by donmccurdy** [comment] 2018-05-21 22:29
Confirmed, three.js assumes the 2nd layout.

**Comment by donmccurdy** [comment] 2018-10-09 00:41
Lost track of this, but we should clarify the spec here.

**Comment by bghgary** [comment] 2018-10-09 00:46
We also have assets that tests this in https://github.com/KhronosGroup/glTF-Asset-Generator/tree/master/Output/Animation_Node.

**Comment by donmccurdy** [comment] 2018-10-11 01:44
Opened #1467.

**Closed as completed** 2018-10-23 14:26 UTC
Labels: bug, specification
