### ISSUE TITLE
drag and drop error. File is not created

### ISSUE THREAD

**Issue by tiCreativeMedia** [KhronosGroup/glTF#399] opened 2015-07-16 13:37 UTC
Hi,

I'm using the default settings for the Maya 2016 plugin and exporting my Collada file. I then try and used the drag and drop utility (in Safari) and nothing happens. No file created.

**Comment by pjcozzi** [comment] 2015-07-18 22:14
Are you using this tool - http://cesiumjs.org/convertmodel.html ?

If so, check out the Troubleshooting section here - https://cesiumjs.org/2014/03/03/Cesium-3D-Models-Tutorial/

**Comment by tiCreativeMedia** [comment] 2015-07-22 23:29
Hi,

Yes, I'm using that web converter. I can open the .dae file in Preview on the mac and it displays correctly. I can't however convert. 

Thanks-
Dave

**Comment by tfili** [comment] 2015-10-05 18:18
This is a problem caused by having `RGB_ZERO` opaque mode. This will be addressed in #105. 

@pjcozzi do you want to keep this open or close it since it's pretty much a dup of #105?

**Comment by pjcozzi** [comment] 2015-10-05 18:28
Let's close as a duplicate.

@tiCreativeMedia thanks again for the report, keep an eye on #105 for the fix.

**Closed by pjcozzi** 2015-10-05 18:28 UTC
Labels: 1.0, converter

**Comment by tiCreativeMedia** [comment] 2015-10-05 18:46
I would say you can close it. I’ve found a workaround at this point.

Thanks
Dave

————————————————————
TI Creative Media
Interactive/Motion/Animation/Sound
 
651 Boylston St. Boston, MA 02116
www.taylorimaging.com
www.ti-3d.com
————————————————————
