### ISSUE TITLE
[PBR extension] Specify formula to calculate BRDF inputs from material properties

### ISSUE THREAD

**Issue by bghgary** [KhronosGroup/glTF#810] opened 2017-01-04 01:33 UTC
The PBR spec does a good job of describing the two material models and their properties, but there is currently no information about how to calculate the BRDF inputs from the material properties, not even in the appendix. There is also little information about this on the web. I realize this math can be inferred from the example shaders, but I propose that we add this information explicitly since all implementations should be doing the same thing. The approximations for the BRDF can differ between implementations. Thoughts?

This is my understanding of the math. All values are in linear space.

**BRDF Inputs**
```
BRDF diffuse (RGBA)
BRDF specular (RGB)
BRDF roughness (float)
```

**Specular-Glossiness**
```
diffuse (RGBA)
specular (RGB)
glossiness (float)
```
where
```
BRDF diffuse = diffuse.rgb * (1 - max(specular.r, specular.g, specular.b))
BRDF specular = specular
BRDF roughness = max((1 - glossiness) ^ 2, epsilon)
```

**Metallic-Roughness**
```
baseColor (RGBA)
metallic (float)
roughness (float)
```
where
```
const dielectricSpecular = rgb(0.04, 0.04, 0.04)
const black = rgb(0, 0, 0)

BRDF diffuse = lerp(baseColor.rgb * (1 - dielectricSpecular.r), black, metallic)
BRDF specular = lerp(dieletricSpecular, baseColor.rgb, metallic)
BRDF roughness = max(roughness ^ 2, epsilon)
```

Is this information accurate?

(Updated: Removed A from specular in specular-glossiness and added .rgb to diffuse and baseColor)

**Comment by pjcozzi** [comment] 2017-01-04 15:30
@mlimper?

+1 from me for including this.

**Comment by javagl** [comment] 2017-01-04 15:42
I already pinged @mlimper and @tsturm vial mail. In fact, this issue *might* be nearly a duplicate of https://github.com/KhronosGroup/glTF/issues/697 , which was also about an example implementation (but much more - admittedly, I didn't read it entirely...). In the end, *some* implementation of the shaders has to exist somewhere - the question might be whether the core (shader) code can be published as a reference implementation.

**Comment by mlimper** [comment] 2017-01-04 16:53
Thanks, this looks very very useful!

We'll put the shader code for a minimalistic example into the appendix as soon as the example implementation is ready - @moneimne is currently working on one.

The original idea for the way the spec works comes from @tsturm, he might be able to judge best if your proposal is accurate. Otherwise, I'd check this as soon as the example implementation is ready, to make sure everything is coherent and then let it check by other contributors that worked on actual implementations.

**Comment by bghgary** [comment] 2017-01-04 18:35
@mlimper Sounds good. Hoping someone can verify the math.

@javagl I think this should be separated out from #697 because the math above should be identical in all implementations. It's different than the BRDF equations because not all implementations will use the same approximations (due to complexity/performance of the equations). Or are we saying we want all implementations to use the same BRDF equations? I'm not sure that's realistic.

**Comment by pjcozzi** [comment] 2017-01-05 14:02
@bghgary set roughness to zero / glossiness to one, is it expected that the curves at the top of the spheres go in the opposite direction like they are mirrored?  Makes it harder to compare.

![image](https://cloud.githubusercontent.com/assets/782098/21683043/9943108c-d325-11e6-83cb-63bd6916ca15.png)

**Comment by sbtron** [comment] 2017-02-14 23:06
Added as explanation part of #830 https://github.com/KhronosGroup/glTF/pull/830/files#diff-a787a363bd89618cda440f087cd0e0e1R798

lets resolve this

**Closed** 2017-04-04 00:21 UTC
Labels: 2.0, extension, PBR, resolved
