### ISSUE TITLE
issue with skinning, skeleton and animation

### ISSUE THREAD

**Issue by bitout** [KhronosGroup/glTF#1374] opened 2018-07-04 03:38 UTC
Implementation a animation system with GLTF is kind of painful. 
Using a big nodes list for both scene graph nodes and skeleton joints is kind of pointless and implementation hell. It could be better if both 'skin'(aka skeleton ) and animation are more localized. With current specification, implementation has to look into the global nodes list to maintain the hierarchy of skeleton and interpolate animation key frame to compute joints matrices. This comes with two limitations, which the implementation has to maintain a global nodes list, and it is also very impossible to share skeleton and animations. 
This can be great improved by moving skin joints out of nodes list and having it inside of skin itself. Hope this could be part of future specification.

**Comment by donmccurdy** [comment] 2019-01-24 00:32
> This comes with two limitations, which the implementation has to maintain a global nodes list, and it is also very impossible to share skeleton and animations.

In many applications the bones are part of the scene graph hierarchy; in other applications they are not. I don't think there is an easy universal solution for that unfortunately.

About sharing the skeleton and animations, that is possible with the current spec (e.g. two meshes can reference the same skin, or two skins can reference the same joints) but I recognize it doesn't enable all possible use cases for shared skeletons. I'm not sure how many applications support shared skeletons, either, but extension proposals (e.g. a `KHR_shared_skins`) or suggestions for the future specification would be welcome. 

For now I'll close this issue as a duplicate of https://github.com/KhronosGroup/glTF/issues/1285.

**Closed by donmccurdy** 2019-01-24 00:32 UTC
Labels: specification/skinning
