### ISSUE TITLE
Parts of a model disappear because blending is enabled

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF#342] opened 2014-12-31 13:31 UTC
I believe this is because the model was exported from SketchUp.  See the attached `kmz` (rename to `zip`) here: https://groups.google.com/forum/#!topic/cesium-dev/snu7ZhSNuwI

To get this model to display, I removed state `3042` from `technique0` and `technique1`.

@fabrobinet do you have time to take a quick look at this?  I can send you a very simple model to reproduce this?

**Comment by fabrobinet** [comment] 2015-01-01 23:12
@pjcozzi this is a duplicate of https://github.com/KhronosGroup/glTF/issues/339  
You can verify that tranparency is 0 is the model you sent me. So the converter is behaving correctly.
Preview on OSX can display the model because they probably work-around by checking the sketchup version , as for a long time time, models exported with sketchup had inverted transparency... We'll probably add such check too but I have to figure out which sketchup version provides correct transparent version.

**Comment by fabrobinet** [comment] 2015-01-01 23:12
so closing now, and let's follow-up in #339

**Closed by fabrobinet** 2015-01-01 23:12 UTC
Labels: bug, converter

**Comment by pjcozzi** [comment] 2015-01-02 15:47
Thanks @fabrobinet.  @tfili will have a look at SketchUp and followup.
