### ISSUE TITLE
Axis convention language in spec

### ISSUE THREAD

**Issue by dubois** [KhronosGroup/glTF#1640] opened 2019-07-11 00:47 UTC
From the spec:
> glTF uses a right-handed coordinate system, that is, the cross product of +X and +Y yields +Z. glTF defines +Y as up. The front of a glTF asset faces +Z.

This doesn't define right-handed because (as also mentioned in #566), x cross y = z is a mathematical identity that holds even in left-handed engines like Unity. To do otherwise would be to require left-handed math libraries in left-handed engines and then the world would end.

This would be more accurate:

> glTF uses a right-handed axis convention; that is, the cross product of right and forward yields up. glTF defines +Y as up, +Z as forward, and -X as right.

The language "+Z as forward, and -X as right" might be a little controversial since there was a lot of discussion in #1043 over whether "forward" even has a meaning (it does!); but nailing this down is critical for tool authors. eg, if two different gltf importers give different results when importing an asset into _insert engine here_, one should be able to authoritatively say which one(s) are buggy. (see also https://github.com/KhronosGroup/UnityGLTF/issues/319)

One could even argue that "front of an asset faces Z" is a bit of an overreach; it goes beyond specifying correct gltf tool behavior (importers, format converters) and starts dictating correct behavior for users creating assets.

Anyway, I'm very happy that glTF has taken a stand against ambiguous axis conventions like "Y up, right handed"! In a past life I worked with robots, and when there is no simple "flip an axis" trick to convert from one convention to another (eg [ROS](https://www.ros.org/reps/rep-0103.html) to Unity) it really brings these problems into sharp relief.

**Comment by donmccurdy** [comment] 2021-04-09 17:39
Based on our own samples, `"+Z as forward, and -X as right"` appears to be correct:

![Screen Shot 2021-04-09 at 10 37 11 AM](https://user-images.githubusercontent.com/1848368/114219520-9b17db80-991f-11eb-90f4-d7c6d55057c8.png)

I think we should make the requested clarification; any concerns with this proposal?

**Comment by MikelSalazar** [comment] 2021-04-10 20:01
The problem is that the standard we are using right now is LPT-ENU and, as the second part of the name implies, it defines the axes as East(X), North(Y) and Up (Z). Plus, in almost every geolocation system, the third axis is defined as altitude/height-over-ellipsoid, because in many applications (i.e. anything related with 2D maps) there is no third dimension.

As a 3D modeler/developer, I prefer the system  defined in GLTF but I can also understand why the situation is as it is. In any case, this is something we have to clarify very well in the documentation.

**Comment by lexaknyazev** [comment] 2021-09-28 15:41
Addressed in the updated spec release.

**Closed by lexaknyazev** 2021-09-28 15:41 UTC

**Comment by jasondavies** [comment] 2023-09-29 08:38
Should this say "+X as right"?  I'm confused by the use of "-X" here.

**Comment by javagl** [comment] 2023-09-29 11:24
Imagine that you are that 'BoomBox' (that CD Player from the image). Then, ...

- +X is pointing in the direction of your **left** hand, 
- -X is pointing in the direction of your **right** hand

I even created <strike>an highly artsy generative AI image with stable diffusion</strike> a crude, squiggly drawing in paint for that in a previous PR, at https://github.com/KhronosGroup/glTF/pull/2139#issuecomment-1093983498

**Comment by javagl** [comment] 2023-09-29 11:26
(And another cross-link: https://github.com/KhronosGroup/glTF/issues/2149 )

**Comment by jasondavies** [comment] 2023-09-29 12:52
Thanks.  Might be worth clarifying by saying "from the point of view of the object" or similar, as it seems to be a common confusion!
