### ISSUE TITLE
(Maybe) a difference of DCCs causes compatibility problems of glTF animation.

### ISSUE THREAD

**Issue by emadurandal** [KhronosGroup/glTF#685] opened 2016-08-18 10:35 UTC
Hi.

I achieved glTF Skinning Animation using my WebGL library at last.
https://cdn.gitcdn.link/cdn/emadurandal/GLBoost/69d12ff60434dd95f06e59ba9745a81b38483aa6/examples/index.html#standalone/loading_gltf_skinning_anim

Then I tried other official models, but sadly, they became nightmare dragons.
![nightmare](https://cloud.githubusercontent.com/assets/3821214/17770588/8111bdac-6579-11e6-8996-1bbd53c72736.jpg)

Thus far, You may think that my library is still immature (or not robust).
But, the problem is a little bit complicated.

I think Cesium.js library has the most accurate and fully functional (and official?) glTF Loader.
Then I tried that with my test glTF file.
But, the result is confusing me.
<img width="463" alt="nightmare2" src="https://cloud.githubusercontent.com/assets/3821214/17770605/8c288acc-6579-11e6-8512-8bb447ddd628.png">

My library can handle the test glTF file properly. So It's not always true that my library’s implementation is wrong.
I use Maya to create my glTF skinning models, and the official glTF animation models seem to be made by Blender.
I think that these confusing results are caused by a difference of DCCs (and their exporters), and my library ([GLBoost](https://github.com/emadurandal/GLBoost)) and [Cesium.js](http://cesiumjs.org) could be optimized for their different data habits.
To diffuse the use of glTF, I feel these compatibility problems need to be resolved.

Sorry for this vague issue. But I desire to help to diffuse glTF format.
I need to ask for your cooperation.

My skinning model Maya file is here. Feel free to use this for testing.
[lady.zip](https://github.com/KhronosGroup/glTF/files/424667/lady.zip)

**Comment by emadurandal** [comment] 2016-08-18 11:19
I'm sure it's not a skinning problem. It must be a bone animation problem.

**Comment by pjcozzi** [comment] 2016-08-18 11:52
@lexaknyazev has been looking at skinning a lot recently for the 1.0.1 spec.  @lexaknyazev any chance you have a minute to check out this model and see if anything jumps out as being wrong compared to the Cesium man model?

**Comment by pjcozzi** [comment] 2016-08-18 11:56
@emadurandal also:
* GLBoost looks like a great project, can I list it in the glTF repo since you are adding glTF support?  Here: https://github.com/KhronosGroup/glTF#webgl-engines

**Comment by pjcozzi** [comment] 2016-08-18 11:56
@emadurandal I also noticed that PBR is on the GLBoost roadmap, feel free to chime in on #643.

**Comment by emadurandal** [comment] 2016-08-18 12:41
@pjcozzi Let me know if you need more information or files for this issue.

> can I list it in the glTF repo since you are adding glTF support? 

Yes, of course. I appreciate it! 😄  I'll also check #643.

**Comment by lexaknyazev** [comment] 2016-08-18 17:05
The first thing that jumps out is
```json
"skeletons": [
    "_koshi",
    "_koshi_L_ashi_tsukene",
    "_koshi_L_ashi_tsukene_L_hiza",
    "_koshi_L_ashi_tsukene_L_hiza_L_ashi",
    "_koshi_R_ashi_tsukene",
    "_koshi_R_ashi_tsukene_R_hiza",
    "_koshi_R_ashi_tsukene_R_hiza_R_ashi",
    "_koshi_sakotsu",
    "_koshi_sakotsu_L_kata",
    "_koshi_sakotsu_L_kata_L_kurubushi",
    "_koshi_sakotsu_L_kata_L_kurubushi_L_te",
    "_koshi_sakotsu_R_kata",
    "_koshi_sakotsu_R_kata_R_kurubushi",
    "_koshi_sakotsu_R_kata_R_kurubushi_R_te",
    "_koshi_sakotsu_neck",
    "_koshi_sakotsu_neck_atama"
],
```

`skeletons` should contain only root nodes of skeleton hierarchies.

**Comment by javagl** [comment] 2016-08-24 18:32
It's hard to guess from the screenshots what might be wrong there. So just minor remarks/guesses:

1. The screenshots reminded me of the ones in http://stackoverflow.com/q/7595982/3182664 . There, the reason was a missing matrix transpose. However, this can hardly be the actual reason here: The error/difference does not seem to be *directly* related to the glTF files themself. I just checked both, the lady and the cesium man...
![animatedlady01](https://cloud.githubusercontent.com/assets/5597569/17942766/0580685e-6a39-11e6-8665-cd956384b05f.png)
...and they seem to work (apart from some "twitching" of the lady at the beginning/end of the animation - this might be a bug somewhere else, maybe remotely related to https://github.com/KhronosGroup/glTF/issues/573 )
2. Could this be caused by something as trivial as a wrong transform for the root node (basically a wrong `bindShapeMatrix`: The viewer assumes an identity transform, and doesn't take the actual transform into account)?
3. The `lady.gltf` passes the validation (as lexaknyazev most likely already tried out)

**Comment by emadurandal** [comment] 2016-08-28 09:49
@javagl Thank you for the testing.

>Could this be caused by something as trivial as a wrong transform for the root node (basically a wrong bindShapeMatrix: The viewer assumes an identity transform, and doesn't take the actual transform into account)?

Yes. My GLBoost library ignores `bindShapeMatrix` since I have no idea to use this property for. (Someone please teach me :cry: )

I tried jgltf-browser on my Mac a couple of minutes ago. But the build steps failed.
Will you please tell me the stable revision?

**Comment by javagl** [comment] 2016-08-28 15:29
The `bindShapeMatrix` has to be the rightmost factor when computing the `jointMatrix`:

    jointMatrix(j) = 
        globalTransformOfNode^-1 *
        globalTransformOfJointNode *
        inverseBindMatrix(j) *
        bindShapeMatrix

Regarding the jgltf-browser: I'll review the build later today / tomorrow (If this does not bring insights, or you think it's a general problem, we can handle this with an issue in JglTF, if you provide more details)

**Comment by emadurandal** [comment] 2016-08-28 16:21
@javagl wow, That's what I really needed. Thank you!
Also, I've never noticed gltfOverview-0.2.0.png.
The computing the joint matrices are written up in the png image.

I regret missing the overview. My GLBoost's computing takes a different approach in my own way without those correct information.
But, It's mysterious that my library can handle animations properly (for only my created data).

> Regarding the jgltf-browser: I'll review the build later today / tomorrow (If this does not bring insights, or you think it's a general problem, we can handle this with an issue in JglTF, if you provide more details)

My two friends and I failed the build. If you don't mind, I'd like to make an issue.

**Comment by javagl** [comment] 2016-08-28 21:33
To avoid "hijacking" this issue with otherwise unrelated topics, I opened a new issue for the build problems: https://github.com/javagl/JglTF/issues/2 

> But, It's mysterious that my library can handle animations properly (for only my created data).

The `bindShapeMatrix` was only a guess. I thought that it might be only a minor issue, because the models are in both cases at least still "recognizable", and not completely messed up (although I wonder what the actual *animation* looks like).  For the CesiumMan, the `bindShapeMatrix` is the identity, whereas for the Lady, it contains a scaling- and translation component. One could now just try out what happens when this is replaced by the identity (i.e. whether it then renders properly in Cesium), but of course, a review-based (less "trial and error") approach would be preferable.

**Comment by pjcozzi** [comment] 2016-08-29 13:53
@javagl @lexaknyazev thanks so much for helping @emadurandal with this.

@emadurandal can we close this?

**Comment by emadurandal** [comment] 2016-08-29 15:20
I very appreciate your cooperation @pjcozzi @lexaknyazev and @javagl . Thank you!

Although there are still some mysteries (what @lexaknyazev commented, and why Cesium.js can't handle my glTF animation data.), I prefer not to disturb you all any longer.

@pjcozzi please close this if you have no concerns. Finally, Thank you again for listing my GLBoost library in the glTF repo. My library is still immature, but I'll continually work to develop it to live up to the name on the list.

**Closed** 2016-08-31 14:55 UTC
Labels: bug, collada2gltf
