### ISSUE TITLE
a mistake in  Coordinate System and Uint in gltf 2.0 Specification

### ISSUE THREAD

**Issue by lyhkop** [KhronosGroup/glTF#2148] opened 2022-04-22 08:39 UTC
there is a mistake in section 3.4 Coordinate System and Uint. in figure 2. +X as right, but it say -X as right in front.

**Comment by lexaknyazev** [comment] 2022-04-22 09:04
Duplicate of #2139. The image will be updated in the next spec revision.

**Closed by lexaknyazev** 2022-04-22 09:04 UTC
