### ISSUE TITLE
Unaligned image in GLB causing issues

### ISSUE THREAD

**Issue by ghost** [KhronosGroup/glTF#1935] opened 2021-01-22 20:11 UTC
I'm reading a KTX2 image in a GLB, whose data is pointed at by a bufferView. The bufferView offset is not 4 byte aligned, which in turn makes the entire KTX2 file misaligned, resulting in a crash on some platforms when trying to read it. It can be fixed by memcpy-ing the buffer view to aligned memory, but that doesn't seem like it would be intended.

Would this be a bug of the tool which created the glb (gltf-transform)? I can see in the spec that accessors and vertex data must be 4 byte aligned, but I can't find that bufferViews must be.

**Comment by donmccurdy** [comment] 2021-01-23 01:41
Does this problem not apply to PNG or JPEG textures as well?

**Comment by stanlo** [comment] 2021-01-23 03:01
I believe the difference is that PNG/JPG is getting decoded from a different library than KTX2, and possibly copying the bytes to temporary aligned storage? But I can confirm that `gltf-transform v0.8.4` will make unaligned bufferViews for PNG/JPG as well.

**Comment by donmccurdy** [comment] 2021-01-23 04:35
Ok, thanks — I've filed https://github.com/donmccurdy/glTF-Transform/issues/171 to go ahead and fix this in glTF-Transform, but this seems like something that should be clarified in the core spec or `KHR_texture_basisu` if it's not there already, so let's keep this issue open.

**Comment by donmccurdy** [comment] 2021-02-01 03:06
This is fixed in v0.9 of glTF-Transform.

**Comment by lexaknyazev** [comment] 2021-02-01 15:40
glTF doesn't have alignment requirements for image buffer views since PNG and JPEG formats do not pad/align their data. We may recommend aligning KTX buffer views to facilitate zero-copy processing but implementations should be resilient anyway.

**Comment by lexaknyazev** [comment] 2021-10-02 14:11
Note that KTX2 needs 8-byte alignment because some of its header fields are 64-bit.

**Comment by zeux** [comment] 2021-10-11 20:25
Should KHR_texture_basisu extension be amended to clarify this requirement?

**Closed** 2023-09-27 15:41 UTC
