### ISSUE TITLE
Can 'inverseBindMatrix' to be calculated by client itself?

### ISSUE THREAD

**Issue by shrinktofit** [KhronosGroup/glTF#1617] opened 2019-05-28 08:28 UTC
I wonder if the 'inverse bind matrix' can be calculated by client use scene graph information.

**Comment by scurest** [comment] 2019-06-19 23:39
No, a file can use whatever `inverseBindMatrices` it wants. They don't have to be the world-to-locals calculated from the `nodes`. The spec mentions at least one such case explicitly

> The default [when no `skin.inverseBindMatrices` property exists] is that each matrix is a 4x4 identity matrix, which implies that inverse-bind matrices were pre-applied.

**Comment by andreasplesch** [comment] 2019-07-03 22:25
also see #1504 . I think the problem is that the spec. gives the impression that the inverse bind matrix could be calculated by the client because the spec. is too vague on how the inverse bind matrix is expected to be applied.

**Comment by lexaknyazev** [comment] 2021-09-28 20:28
Closing since the OP question has been answered.

**Closed by lexaknyazev** 2021-09-28 20:28 UTC
