### ISSUE TITLE
collada2gltf - optionally preserve vertex colors

### ISSUE THREAD

**Issue by torleif** [KhronosGroup/glTF#528] opened 2016-01-24 05:53 UTC
when using the collada2gltf tool, it's stripping the vertex color information from the resulting gltf file

**Comment by AndresCuervo** [comment] 2017-07-20 19:41
Is there a way to do this? I just ran into this problem, and was wondering if there's a workaround, possibly another conversion tool for now?

**Comment by donmccurdy** [comment] 2017-07-20 19:55
There is more information in this bug on the COLLADA2GLTF repo: https://github.com/KhronosGroup/COLLADA2GLTF/issues/12

Modifying COLLADA2GLTF with the suggested fix has worked for me before, but I don't know enough about the code to say if it is safe to merge.

**Comment by donmccurdy** [comment] 2017-07-20 19:58
The [blender exporter](https://github.com/KhronosGroup/glTF-Blender-Exporter) should also include vertex colors, but may take some tweaking (per the exporter's docs). Going to close this bug and consider it a duplicate of the COLLADA2GLTF#12.

**Closed by donmccurdy** 2017-07-20 19:58 UTC
Labels: bug, collada2gltf
