### ISSUE TITLE
 Deprecate unsigned byte index buffer in future glTF

### ISSUE THREAD

**Issue by McNopper** [KhronosGroup/glTF#1884] opened 2020-10-17 08:13 UTC
In general, only unsigned integers of size 16 and 32 are supported as indices. 8 bit is only supported as an extension in Vulkan.

Metal: https://developer.apple.com/documentation/metal/mtlindextype
WebGPU: https://gpuweb.github.io/gpuweb/#enumdef-gpuindexformat
Vulkan: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VkIndexType

To reduce the complexity for a glTF renderer, the unsigned byte index buffers should be deprecated.

**Comment by javagl** [comment] 2020-10-18 13:30
This was brought up in a similar form quite a while ago: https://github.com/KhronosGroup/glTF-Sample-Models/issues/187 (I wonder whether the expected simplification is worth a breaking change here, but am not a renderer implementation expert...)

**Comment by McNopper** [comment] 2020-10-18 21:20
With these modern API's, the conversion of the byte buffer is not done automatically anymore. One does have to implement, which is not a big deal. But could be avoided.
Maybe we can first introduce a `KHR_simplicity` extension, where e.g. byte index buffers are not allowed :-)

**Comment by lexaknyazev** [comment] 2020-10-18 21:31
Deprecating uint8 index type seems like a good step for now. We could add an implementation note to the current spec and a validation warning that this format is not recommended.

**Comment by emackey** [comment] 2020-11-05 00:22
Related to (or duplicate with?) #1471.

**Comment by javagl** [comment] 2020-11-05 14:25
@emackey I'd vote to close this as a duplicate of the other. I don't see any information here that is *not* contained in the other.

**Closed** 2021-01-02 20:41 UTC
Labels: breaking change
