### ISSUE TITLE
'texture.source' property is not required, but no default value is specified?

### ISSUE THREAD

**Issue by tomolt** [KhronosGroup/glTF#1226] opened 2018-01-27 20:04 UTC
From the spec:

| |Type | Description | Required |
| --| -- | -- | -- |
source | integer | The index of the image used by this texture. | No

I can't seem to find any information on how a complying GLTF2 loader should actually behave if texture.source is not defined.
Usually, the spec states a default value to be used instead, as in texture.sampler:

| |Type | Description | Required |
| --| -- | -- | -- |
sampler	| integer |	The index of the sampler used by this texture. When undefined, a sampler with repeat wrapping and auto filtering should be used. |	No

However, I can't find any information on a default value for texture.source, neither in the properties reference nor in the *Texture Data* section.

The only other options I might be missing are that texture.source is not needed when some
other properties are set (but I can't find anything on that either, and it would be kind of absurd to exist anyway) or that the texture is supposed to be filled with zeroes, much like a buffer without uri (or that's at least my understanding of how a buffer without uri behaves).

I believe the intended behavior to be simply using the first / only image in the GLTF file *per default* as the source, but I am not sure.

Can someone please clarify this?

Thank you in advance.

**Comment by zellski** [comment] 2018-01-27 21:11
I am curious, too. The use case I've assumed is that there are times when you author a model intending to provide a texture source at run-time (perhaps a photo frame), and you want artists to be able to control and export everything except the final actual pixel array. But that's just a guess.

As far as I can see, THREE.GLTFLoader simply NPEs if it's missing, so I'm going to suggest it's a bit of an edge case to leave it undefined.

**Comment by takahirox** [comment] 2018-01-28 10:06
What first came into my head is framebuffer.
They don't need an input image.

**Comment by tomolt** [comment] 2018-01-28 10:41
But why make framebuffers so implicit ?
Wouldn't it be much more in GLTF's spirit to explicitly define an array of framebuffers for the entire file
and then have the texture object either supply a 'image' property (instead of the current 'source' property) or a 'framebuffer' property pointing at the framebuffer you should use.
That way, it might be easier for loaders to bind their framebuffers to the textures.
Also, I'm sure the spec right now doesn't even mention framebuffers, so having them be an undocumented edge-case seems kind of wrong to me.

**Comment by takahirox** [comment] 2018-01-28 12:23
I just mentioned what texture without image can be for. I'd like to know the actual purpose of non-image-required texture in glTF spec and expected use case, too.

**Comment by javagl** [comment] 2018-01-29 02:58
This is actually a duplicate of https://github.com/KhronosGroup/glTF/issues/1016 , but ... there's not much information, and some more details should probably be added here, there, or in the spec.

**Comment by pjcozzi** [comment] 2018-02-28 16:23
Bump @lexaknyazev?

**Comment by lexaknyazev** [comment] 2018-02-28 16:45
@pjcozzi 
I still don't have an ultimate answer for this case. It falls under "undefined behavior", imo.
We can either propose a recommend fallback (e.g. a particular color) or explicitly say that engines may fail on such assets (this could be a validation warning).

**Comment by pjcozzi** [comment] 2018-02-28 17:01
No strong preference.  Up to you IMO.

**Comment by lexaknyazev** [comment] 2018-02-28 17:04
Could we check with existing engines what do they do with such models? 
It'd be nice to have them from the asset generator. 
/cc @bghgary

**Comment by bghgary** [comment] 2018-02-28 20:31
> Could we check with existing engines what do they do with such models?

Current glTF loader in BabylonJS will throw an error when texture.source is missing or invalid.

> It'd be nice to have them from the asset generator.

Yes, eventually. The asset generator currently only handles positive cases. This would fall into a negative case.

**Comment by takahirox** [comment] 2018-02-28 21:35
In Three.js, glTF loader throws an error if texture.source is missing.

**Comment by Jakouf** [comment] 2018-07-11 08:57
Are there any new information about that? In my opinion the source should be required, otherwise the texture object doesn't really make sense to me.

**Comment by emackey** [comment] 2018-07-11 19:19
Babylon, Cesium, and ThreeJS all throw uncaught exceptions when reading a `texture` object that does not contain a `source`.

@bghgary @lexaknyazev Can we just change it to required?

**Comment by donmccurdy** [comment] 2018-07-11 19:48
I think the original motivation had to do with supporting cubemaps in the future? See https://github.com/KhronosGroup/glTF/issues/1366

**Comment by emackey** [comment] 2019-01-26 04:51
In https://github.com/KhronosGroup/glTF/pull/1458#issuecomment-457789140 @lexaknyazev points out that we can't make this required.  The DDS and WebP extensions rely on this being optional.

**Comment by pjcozzi** [comment] 2019-01-29 00:01
@emackey do you suggest that we close this?  add an implementation note?  something else?

**Comment by emackey** [comment] 2019-01-29 14:37
How about this:

#### texture.source

The index of the image used by this texture.  When undefined, an extension must supply an alternate texture source.

**Closed** 2019-02-27 18:38 UTC
Labels: specification
