### ISSUE TITLE
Clarify material, pbrMetallicRoughness, textureInfo objects

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/glTF#923] opened 2017-04-21 14:33 UTC
@sbtron @bghgary 

- Unlike other glTF objects, `pbrMetallicRoughness` and `textureInfo` don't inherit from `glTFProperty` so they haven't `extras` or `extensions`. Is it intentional?
- Should `material.alphaCutoff` maximum value be limited to `1.0`?

**Comment by bghgary** [comment] 2017-04-21 16:08
> Unlike other glTF objects, pbrMetallicRoughness and textureInfo don't inherit from glTFProperty so they haven't extras or extensions. Is it intentional?

These are intended to be interim objects. I would expect extras/extensions to be added at the material level. But looks like everything else "inherits" from glTFProperty, so I wouldn't be opposed to doing that for these as well.

> Should material.alphaCutoff maximum value be limited to 1.0?

No. This was intentional. The issue is with the "the alpha value is greater than or equal" clause in the [Alpha Coverage](https://github.com/KhronosGroup/glTF/tree/2.0/specification/2.0#alpha-coverage) section. If someone wanted to make everything transparent, they can set this value to something greater than 1 to avoid the "equal" part being true. This is mainly useful for animations when they can target the alpha value which 2.0 currently can't do, but I can easily imagine adding this functionality in the future or via an extension.

**Comment by lexaknyazev** [comment] 2017-04-21 18:50
@bghgary 
> I wouldn't be opposed to doing that for these as well.

OK. I'll update schemas.

Could you add something about
> If someone wanted to make everything transparent, they can set this value to something greater than 1...

to property description? I think this could be overlooked by implementations.

**Comment by bghgary** [comment] 2017-04-21 21:47
Meant to create a PR but accidentally committed directly. Let me know if it's okay. https://github.com/KhronosGroup/glTF/commit/e878126671bdb2ab235d1f0e232a4f2741916530

**Comment by lexaknyazev** [comment] 2017-04-21 21:49
That's just a description. It's okay.

**Closed** 2017-04-21 21:50 UTC
Labels: 2.0, resolved, specification
