### ISSUE TITLE
Clarify the occlusion color

### ISSUE THREAD

**Issue by peteroupc** [KhronosGroup/glTF#915] opened 2017-04-15 15:35 UTC
The occlusion strength specification says:

> A scalar multiplier controlling the amount of occlusion applied. A value of 0.0 means no occlusion. A value of 1.0 means full occlusion. This value affects the resulting color using the formula: `occludedColor = lerp(color, color * <sampled occlusion texture value>, <occlusion strength>)`. This value is ignored if the corresponding texture is not specified. This value is linear.

What `color` is meant here?  Is it the `c_diff` color? Is it the final output color?  Is it something else?

**Comment by McNopper** [comment] 2017-05-26 15:30
From my understaning it is c_diff.

**Comment by pjcozzi** [comment] 2017-10-19 16:47
@sbtron has kindly volunteered to make the updates and point to the reference implementation.

**Comment by pjcozzi** [comment] 2017-12-24 00:53
> @sbtron has kindly volunteered to make the updates and point to the reference implementation.

@sbtron were these updates made?  OK to close this?

**Comment by lexaknyazev** [comment] 2018-11-23 11:51
@sbtron @bghgary 
Was the spec updated?

**Comment by donmccurdy** [comment] 2018-11-23 19:14
Opened https://github.com/KhronosGroup/glTF/pull/1499.

From *[The Joy of a little "Ambience"...](http://mentalraytips.blogspot.com/2008/11/joy-of-little-ambience.html)*, I found this diagram helpful:

![ao-explain](https://user-images.githubusercontent.com/1848368/48957664-d95afe80-ef0e-11e8-9441-d8c7f19bba79.jpg)

**Comment by donmccurdy** [comment] 2018-11-24 20:31
On second look, I don`t think AO is multiplied against c<sub>diff</sub> (diffuse color), if defined as we do in the spec:

> c<sub>diff</sub> = lerp(baseColor.rgb * (1 - dielectricSpecular.r), black, metallic)

If we're multiplying AO against base color, or output color for that matter, the AO will affect both direct and indirect light, which it shouldn't. It would be more correct to say that AO is modulates _indirect_ diffuse color, which the spec does not define as a specific term. I think that's equivalent to saying it is a multiplier against the indirect light affecting a point.

**Comment by emackey** [comment] 2018-12-05 02:37
Related:
https://github.com/KhronosGroup/glTF-WebGL-PBR/issues/104.
https://github.com/KhronosGroup/glTF-WebGL-PBR/issues/106,
https://github.com/KhronosGroup/glTF-Blender-IO/issues/123#issuecomment-443541341

It does appear that it would be (somewhat) more correct to limit the influence of the occlusion channel to just IBL and indirect lighting, and exclude its effects from punctual light sources.

This would be a breaking change from our current reference shaders (both the "classic" glTF-WebGL-PBR and the new UX3D reference implementation), which apply occlusion after all other lighting and specular contributions have been taken into account.

Further, it appears at least some implementations, including Blender 2.80, currently don't offer a way to separate the effects of occlusion on IBL vs lights.  So if we make this change, it won't be reflected in those implementations.

**Comment by donmccurdy** [comment] 2018-12-05 17:58
Another related thread: https://github.com/KhronosGroup/glTF/issues/1427, and a few more references:

Our spec also claims:

> "Higher [occlusion] values indicate areas that should receive full indirect lighting and lower values indicate no indirect lighting."

Unity:

> "Ambient occlusion (AO) approximates how much ambient lighting (lighting not coming from a specific direction) can hit a point on a surface."

ThreeJS:

- envMap reflections are not occluded by aoMap https://github.com/mrdoob/three.js/issues/8107
- Restricting ambient occlusion to modulate only indirect lighting https://github.com/mrdoob/three.js/issues/6271

From the [Frostbite paper](https://seblagarde.files.wordpress.com/2015/07/course_notes_moving_frostbite_to_pbr_v32.pdf) we've referenced in KHR_lights_punctual: 

> Medium to large scale occlusion is only applied on indirect lighting.

The paper mentions several forms of occlusion:

- **Direct diffuse** Diffuse micro-occlusion
- **Indirect diffuse** Diffuse micro-occlusion, min(bakedAO, HBAO)
- **Direct specular** Fresnel reflectance modification through specular micro-occlusion
- **Indirect specular** Fresnel reflectance modification through specular micro-occlusion then com-
puteSpecularOcclusion(NdotV, min(bakedAO, HBAO), roughness)

**Comment by donmccurdy** [comment] 2018-12-05 17:59
Classic glTF-WebGL-PBR was never a normative reference, and the new UX3D implementation is incomplete, so I don't see this as a breaking change.

**Comment by emackey** [comment] 2018-12-12 21:18
Overall, I think this change (to remove baked occlusion from direct light sources) is a good one, and it would be appropriate to update the reference viewer to take this into consideration.

I'm not sure how to change the wording of the spec to account for this.  Several implementations, including Blender 2.80, can't conform to this new requirement.  This is another case where our desire to have glTF look identical everywhere is at odds with the reality that many rendering engines aren't flexible enough to produce pixel-perfect matches for reference formulas.

**Comment by donmccurdy** [comment] 2018-12-16 01:32
> Several implementations, including Blender 2.80, can't conform to this new requirement. 

I think Blender 2.80 is more conformant to this requirement than not, actually. Consider three needs that Blender users might have:

1. Previewing dynamic AO while modeling.
2. Baking AO to a texture.
3. Previewing baked AO before export or after import.

In cases (1) and (2), Blender's AO does not affect direct lighting. I couldn't find documentation on this, but a quick test (enabling/disabling AO under primarily direct lighting) seems to confirm:

![2d4b4f81-7904-4109-aafb-60445c93d416-95355-0002f77497d38e48](https://user-images.githubusercontent.com/1848368/50048972-5ef54880-008e-11e9-97c2-7befa52f73d6.gif)

In case (3), the problem is simply that Blender doesn't have a real socket to connect AO, and the only workaround we've got (multiplying against Principled BSDF output) gives results that are inconsistent with (1) and (2).

In some future version of PBR we could add factor to influence this, like Unity and BabylonJS provide. It would be helpful to get some numbers about how often that is used, to inform the decision...

For the current spec, are we comfortable with making "AO affects indirect lighting" a formal requirement? I agree the normative wording may be tricky. Another option would be to put the requirement in the `KHR_punctual_lights` extension, perhaps?

**Comment by sbtron** [comment] 2019-01-23 22:01
Also linking to reference viewer https://github.com/KhronosGroup/glTF-WebGL-PBR/issues/138

**Comment by bghgary** [comment] 2019-02-01 19:06
> For the current spec, are we comfortable with making "AO affects indirect lighting" a formal requirement? I agree the normative wording may be tricky. Another option would be to put the requirement in the KHR_punctual_lights extension, perhaps?

I'm okay with either of these options. I am planning on updating the Babylon implementation to make it only affect indirect lighting.

**Comment by JNoguer-ALG** [comment] 2019-02-04 18:35
For reference, here is how popular real time renderers/tools handle AO today:

**Marmoset Toolbag**
- AO affects diffuse lighting from all sources
- AO doesn’t affect metals at all
- AO doesn’t affect specular term

**Unreal Engine 4**
- AO affects diffuse lighting from ambient lighting, direct lighting is not affected
- AO affects rough metals only (0.0 roughness = no AO, 0.3 roughness = full AO)
- AO doesn’t affect specular term

**Unity 2018.3**
- AO affects diffuse lighting from ambient lighting, direct lighting is not affected
- AO affects all metals
- AO doesn’t affect specular term

**Sketchfab**
- AO affects diffuse lighting from ambient lighting, direct lighting is not affected
- AO doesn’t affect metals at all
- AO doesn’t affect specular term

**Substance Designer**
- AO affects diffuse lighting from ambient lighting, direct lighting is not affected
- AO affects all metals
- AO doesn’t affect specular term

**Substance Painter**
- AO affects diffuse lighting from ambient lighting (direct lighting not supported)
- AO affects rough metals only (0.0 roughness = no AO, 1.0 roughness = full AO)
- AO affects specular term
 
Unreal seems to be the package that's the closest to a ground truth at the moment.

**Comment by donmccurdy** [comment] 2019-02-11 23:32
Outstanding summary, thank you for digging that information up, @JNoguer-ALG. 🙂

At minimum, this seems like pretty good consensus for `AO affects diffuse lighting from ambient lighting, direct lighting is not affected`. Are we comfortable putting that in the spec? It would be ideal to clarify the other points, or at least to mention the range of possibilities that implementers should expect.

**Comment by romainguy** [comment] 2020-01-14 22:59
It would worth checking out what Unity HDRP does as well. I believe they do what we do in Filament:

- AO affects diffuse lighting from ambient lighting, direct lighting is not affected
- Specular AO is derived from AO and is applied to the specular term (and therefore metals)

**Comment by echadwick-wayfair** [comment] 2020-01-15 15:57
Deriving the specular AO would be a nice addition. 

Unreal has a before/after image demo showing a similar treatment. 
https://docs.unrealengine.com/en-US/Engine/Rendering/LightingAndShadows/BentNormalMaps/#reflectionocclusion

They're using a Bent Normal Map, but it seems like for efficiency the darker ends of the AO could be repurposed for specular occlusion.

**Comment by romainguy** [comment] 2020-01-15 15:59
I have a before/after as well (animated GIF on Twitter): https://twitter.com/romainguy/status/1129562303257501697

It helps a lot on metals and highly reflective areas (see under the hose or the rim of the goggles for instance).

**Comment by donmccurdy** [comment] 2020-12-01 23:08
Have we decided whether, and how, IBL should be affected by AO? When IBL produces both a diffuse and a specular contribution to the scene's lighting, presumably the diffuse term should certainly be affected by AO, and the specular term effect is less certain (per earlier comments)?

**Comment by romainguy** [comment] 2020-12-01 23:25
Specular AO can be derived from diffuse AO. You can find our implementation (based on Lagarde's when you don't have bent normals and on Jimenez's when you do have a bent normals) here: https://github.com/google/filament/blob/main/shaders/src/ambient_occlusion.fs

**Comment by donmccurdy** [comment] 2020-12-01 23:47
I'm hoping to reach normative language, if possible – if specular AO can be derived from diffuse AO, is this a reasonable set of guidelines?

- Occlusion **MUST** affect diffuse lighting from indirect sources, such as IBL and ambient lighting.
- Occlusion **MUST NOT** affect direct lighting, such as punctual light sources.
- Occlusion **SHOULD** affect specular lighting contributions, such as IBL, by deriving specular occlusion.

**Comment by romainguy** [comment] 2020-12-01 23:52
👍

**Comment by echadwick-wayfair** [comment] 2021-02-03 15:26
The 3rd bullet seems a bit contradictory with the 2nd bullet, because punctual lights create specular too. Perhaps the 3rd bullet should specifically omit punctual?

---

I noticed some differences in how the glTF Sample VIewer and Babylon.js render ambient occlusion, so I did some testing and thought I'd share. I'm not quite sure what the objective truth should be, but there are a few things I noticed. This is using the Amazon directional HDR. 

1. Ambient occlusion should occlude specular reflection, per comments above. Babylon.js seems to do this, making a dark occlusion under the spheres, however I'm not sure if this should also happen on rough metal?

2. Ambient occlusion on non-metals seems to be better in glTF Sample Viewer than in Babylon.js, seems to show a fuller range.

A couple more non-AO issues:
3. The white non-metal spheres show some shading artifacts in the glTF Sample Viewer, looks like it's related to the model resolution?
4. White rough metal in the glTF Sample Viewer doesn't seem to be conserving energy, seems to be a darker gray than maybe it should be.

![2021-01-28 17_01_39-glTF Sample Viewer](https://user-images.githubusercontent.com/40177036/106768082-937b4400-6609-11eb-971e-e2587612e051.jpg)

![2021-01-28 17_02_25-Babylon js - OcclusionSpheres gltf](https://user-images.githubusercontent.com/40177036/106768096-970ecb00-6609-11eb-8c24-24dc7d8817b7.jpg)

[OcclusionSpheres_glTF.zip](https://github.com/KhronosGroup/glTF/files/5919483/OcclusionSpheres_glTF.zip)

**Closed** 2021-09-27 21:30 UTC
Labels: specification, 2.0, needs discussion
