### ISSUE TITLE
Area lights or sphere lights

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF#1475] opened 2018-10-31 20:53 UTC
Has anyone implemented area lights or sphere lights in PBR for glTF?

Sphere lights are discussed on page 15 of [Real Shading in Unreal Engine 4 by Brian Karis, Epic Games](https://cdn2.unrealengine.com/Resources/files/2013SiggraphPresentationsNotes-26915738.pdf).  But I'm wondering if anyone has turned the formulas into actual open-source shader code for sphere lights.

**Comment by donmccurdy** [comment] 2018-10-31 21:01
Nothing formal, but /cc https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/136.

**Comment by donmccurdy** [comment] 2021-04-19 04:38
Closing as duplicate of https://github.com/KhronosGroup/glTF/issues/1940. Also see proposal in https://github.com/KhronosGroup/glTF/pull/1948.

**Closed by donmccurdy** 2021-04-19 04:38 UTC
